# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'EnglishWordLearningAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for EnglishWordLearningAI

    pod 'GoogleMLKit/Translate', '3.2.0'

  target 'EnglishWordLearningAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EnglishWordLearningAIUITests' do
    # Pods for testing
  end

end